// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: greetings.proto

package greetings

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SayHello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayHello) Reset() {
	*x = SayHello{}
	mi := &file_greetings_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHello) ProtoMessage() {}

func (x *SayHello) ProtoReflect() protoreflect.Message {
	mi := &file_greetings_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHello.ProtoReflect.Descriptor instead.
func (*SayHello) Descriptor() ([]byte, []int) {
	return file_greetings_proto_rawDescGZIP(), []int{0}
}

func (x *SayHello) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SayHi struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayHi) Reset() {
	*x = SayHi{}
	mi := &file_greetings_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayHi) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHi) ProtoMessage() {}

func (x *SayHi) ProtoReflect() protoreflect.Message {
	mi := &file_greetings_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHi.ProtoReflect.Descriptor instead.
func (*SayHi) Descriptor() ([]byte, []int) {
	return file_greetings_proto_rawDescGZIP(), []int{1}
}

func (x *SayHi) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SayStop struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayStop) Reset() {
	*x = SayStop{}
	mi := &file_greetings_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayStop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayStop) ProtoMessage() {}

func (x *SayStop) ProtoReflect() protoreflect.Message {
	mi := &file_greetings_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayStop.ProtoReflect.Descriptor instead.
func (*SayStop) Descriptor() ([]byte, []int) {
	return file_greetings_proto_rawDescGZIP(), []int{2}
}

func (x *SayStop) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_greetings_proto protoreflect.FileDescriptor

const file_greetings_proto_rawDesc = "" +
	"\n" +
	"\x0fgreetings.proto\x12\tgreetings\"\x1e\n" +
	"\bSayHello\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x1b\n" +
	"\x05SayHi\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x1d\n" +
	"\aSayStop\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04nameB\x12Z\x10actsvr/greetingsb\x06proto3"

var (
	file_greetings_proto_rawDescOnce sync.Once
	file_greetings_proto_rawDescData []byte
)

func file_greetings_proto_rawDescGZIP() []byte {
	file_greetings_proto_rawDescOnce.Do(func() {
		file_greetings_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_greetings_proto_rawDesc), len(file_greetings_proto_rawDesc)))
	})
	return file_greetings_proto_rawDescData
}

var file_greetings_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_greetings_proto_goTypes = []any{
	(*SayHello)(nil), // 0: greetings.SayHello
	(*SayHi)(nil),    // 1: greetings.SayHi
	(*SayStop)(nil),  // 2: greetings.SayStop
}
var file_greetings_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_greetings_proto_init() }
func file_greetings_proto_init() {
	if File_greetings_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_greetings_proto_rawDesc), len(file_greetings_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_greetings_proto_goTypes,
		DependencyIndexes: file_greetings_proto_depIdxs,
		MessageInfos:      file_greetings_proto_msgTypes,
	}.Build()
	File_greetings_proto = out.File
	file_greetings_proto_goTypes = nil
	file_greetings_proto_depIdxs = nil
}
