// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: loader.proto

package loader

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cmd           string                 `protobuf:"bytes,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_loader_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_loader_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_loader_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

type Progress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Src           string                 `protobuf:"bytes,1,opt,name=src,proto3" json:"src,omitempty"`
	State         int32                  `protobuf:"varint,3,opt,name=state,proto3" json:"state,omitempty"`        // WorkerState
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`     // error message if state is "error"
	Progress      float64                `protobuf:"fixed64,5,opt,name=progress,proto3" json:"progress,omitempty"` // 0.0 to 1.0
	Success       int64                  `protobuf:"varint,6,opt,name=success,proto3" json:"success,omitempty"`    // number of successful imports
	Fail          int64                  `protobuf:"varint,7,opt,name=fail,proto3" json:"fail,omitempty"`          // number of failed imports
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Progress) Reset() {
	*x = Progress{}
	mi := &file_loader_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Progress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Progress) ProtoMessage() {}

func (x *Progress) ProtoReflect() protoreflect.Message {
	mi := &file_loader_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Progress.ProtoReflect.Descriptor instead.
func (*Progress) Descriptor() ([]byte, []int) {
	return file_loader_proto_rawDescGZIP(), []int{1}
}

func (x *Progress) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *Progress) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *Progress) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Progress) GetProgress() float64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *Progress) GetSuccess() int64 {
	if x != nil {
		return x.Success
	}
	return 0
}

func (x *Progress) GetFail() int64 {
	if x != nil {
		return x.Fail
	}
	return 0
}

var File_loader_proto protoreflect.FileDescriptor

const file_loader_proto_rawDesc = "" +
	"\n" +
	"\floader.proto\x12\x06loader\"\x1b\n" +
	"\aRequest\x12\x10\n" +
	"\x03cmd\x18\x01 \x01(\tR\x03cmd\"\x96\x01\n" +
	"\bProgress\x12\x10\n" +
	"\x03src\x18\x01 \x01(\tR\x03src\x12\x14\n" +
	"\x05state\x18\x03 \x01(\x05R\x05state\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x1a\n" +
	"\bprogress\x18\x05 \x01(\x01R\bprogress\x12\x18\n" +
	"\asuccess\x18\x06 \x01(\x03R\asuccess\x12\x12\n" +
	"\x04fail\x18\a \x01(\x03R\x04failB\x0fZ\ractsvr/loaderb\x06proto3"

var (
	file_loader_proto_rawDescOnce sync.Once
	file_loader_proto_rawDescData []byte
)

func file_loader_proto_rawDescGZIP() []byte {
	file_loader_proto_rawDescOnce.Do(func() {
		file_loader_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_loader_proto_rawDesc), len(file_loader_proto_rawDesc)))
	})
	return file_loader_proto_rawDescData
}

var file_loader_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_loader_proto_goTypes = []any{
	(*Request)(nil),  // 0: loader.Request
	(*Progress)(nil), // 1: loader.Progress
}
var file_loader_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_loader_proto_init() }
func file_loader_proto_init() {
	if File_loader_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_loader_proto_rawDesc), len(file_loader_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_loader_proto_goTypes,
		DependencyIndexes: file_loader_proto_depIdxs,
		MessageInfos:      file_loader_proto_msgTypes,
	}.Build()
	File_loader_proto = out.File
	file_loader_proto_goTypes = nil
	file_loader_proto_depIdxs = nil
}
