// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: trjd.proto

package trjd

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkId        string                 `protobuf:"bytes,1,opt,name=workId,proto3" json:"workId,omitempty"`
	Src           string                 `protobuf:"bytes,2,opt,name=src,proto3" json:"src,omitempty"`
	DstHost       string                 `protobuf:"bytes,3,opt,name=dstHost,proto3" json:"dstHost,omitempty"`
	DstPort       int32                  `protobuf:"varint,4,opt,name=dstPort,proto3" json:"dstPort,omitempty"`
	DstUser       string                 `protobuf:"bytes,5,opt,name=dstUser,proto3" json:"dstUser,omitempty"`
	DstPass       string                 `protobuf:"bytes,6,opt,name=dstPass,proto3" json:"dstPass,omitempty"`
	DstTable      string                 `protobuf:"bytes,7,opt,name=dstTable,proto3" json:"dstTable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportRequest) Reset() {
	*x = ImportRequest{}
	mi := &file_trjd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportRequest) ProtoMessage() {}

func (x *ImportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trjd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportRequest.ProtoReflect.Descriptor instead.
func (*ImportRequest) Descriptor() ([]byte, []int) {
	return file_trjd_proto_rawDescGZIP(), []int{0}
}

func (x *ImportRequest) GetWorkId() string {
	if x != nil {
		return x.WorkId
	}
	return ""
}

func (x *ImportRequest) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *ImportRequest) GetDstHost() string {
	if x != nil {
		return x.DstHost
	}
	return ""
}

func (x *ImportRequest) GetDstPort() int32 {
	if x != nil {
		return x.DstPort
	}
	return 0
}

func (x *ImportRequest) GetDstUser() string {
	if x != nil {
		return x.DstUser
	}
	return ""
}

func (x *ImportRequest) GetDstPass() string {
	if x != nil {
		return x.DstPass
	}
	return ""
}

func (x *ImportRequest) GetDstTable() string {
	if x != nil {
		return x.DstTable
	}
	return ""
}

type ImportProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkId        string                 `protobuf:"bytes,1,opt,name=workId,proto3" json:"workId,omitempty"`
	Src           string                 `protobuf:"bytes,2,opt,name=src,proto3" json:"src,omitempty"`
	State         int32                  `protobuf:"varint,3,opt,name=state,proto3" json:"state,omitempty"`        // WorkerState
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`     // error message if state is "error"
	Progress      float64                `protobuf:"fixed64,5,opt,name=progress,proto3" json:"progress,omitempty"` // 0.0 to 1.0
	Success       int64                  `protobuf:"varint,6,opt,name=success,proto3" json:"success,omitempty"`    // number of successful imports
	Fail          int64                  `protobuf:"varint,7,opt,name=fail,proto3" json:"fail,omitempty"`          // number of failed imports
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportProgress) Reset() {
	*x = ImportProgress{}
	mi := &file_trjd_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportProgress) ProtoMessage() {}

func (x *ImportProgress) ProtoReflect() protoreflect.Message {
	mi := &file_trjd_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportProgress.ProtoReflect.Descriptor instead.
func (*ImportProgress) Descriptor() ([]byte, []int) {
	return file_trjd_proto_rawDescGZIP(), []int{1}
}

func (x *ImportProgress) GetWorkId() string {
	if x != nil {
		return x.WorkId
	}
	return ""
}

func (x *ImportProgress) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *ImportProgress) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *ImportProgress) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ImportProgress) GetProgress() float64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *ImportProgress) GetSuccess() int64 {
	if x != nil {
		return x.Success
	}
	return 0
}

func (x *ImportProgress) GetFail() int64 {
	if x != nil {
		return x.Fail
	}
	return 0
}

var File_trjd_proto protoreflect.FileDescriptor

const file_trjd_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"trjd.proto\x12\x04trjd\"\xbd\x01\n" +
	"\rImportRequest\x12\x16\n" +
	"\x06workId\x18\x01 \x01(\tR\x06workId\x12\x10\n" +
	"\x03src\x18\x02 \x01(\tR\x03src\x12\x18\n" +
	"\adstHost\x18\x03 \x01(\tR\adstHost\x12\x18\n" +
	"\adstPort\x18\x04 \x01(\x05R\adstPort\x12\x18\n" +
	"\adstUser\x18\x05 \x01(\tR\adstUser\x12\x18\n" +
	"\adstPass\x18\x06 \x01(\tR\adstPass\x12\x1a\n" +
	"\bdstTable\x18\a \x01(\tR\bdstTable\"\xb4\x01\n" +
	"\x0eImportProgress\x12\x16\n" +
	"\x06workId\x18\x01 \x01(\tR\x06workId\x12\x10\n" +
	"\x03src\x18\x02 \x01(\tR\x03src\x12\x14\n" +
	"\x05state\x18\x03 \x01(\x05R\x05state\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x1a\n" +
	"\bprogress\x18\x05 \x01(\x01R\bprogress\x12\x18\n" +
	"\asuccess\x18\x06 \x01(\x03R\asuccess\x12\x12\n" +
	"\x04fail\x18\a \x01(\x03R\x04failB\rZ\vactsvr/trjdb\x06proto3"

var (
	file_trjd_proto_rawDescOnce sync.Once
	file_trjd_proto_rawDescData []byte
)

func file_trjd_proto_rawDescGZIP() []byte {
	file_trjd_proto_rawDescOnce.Do(func() {
		file_trjd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trjd_proto_rawDesc), len(file_trjd_proto_rawDesc)))
	})
	return file_trjd_proto_rawDescData
}

var file_trjd_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_trjd_proto_goTypes = []any{
	(*ImportRequest)(nil),  // 0: trjd.ImportRequest
	(*ImportProgress)(nil), // 1: trjd.ImportProgress
}
var file_trjd_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_trjd_proto_init() }
func file_trjd_proto_init() {
	if File_trjd_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trjd_proto_rawDesc), len(file_trjd_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_trjd_proto_goTypes,
		DependencyIndexes: file_trjd_proto_depIdxs,
		MessageInfos:      file_trjd_proto_msgTypes,
	}.Build()
	File_trjd_proto = out.File
	file_trjd_proto_goTypes = nil
	file_trjd_proto_depIdxs = nil
}
